### PR TITLE
fix: Fixed the memory issue

### LINKED ISSUE #465: check_circuit should handle recursion
As discussed by @Rumata888 and @vezenovm, our `check_circuit` functions don't work with recursive verifier circuits.

### PR DESCRIPTION
**Pull request by Rumata888**
# Description
Fixed the issue we had with Ultra RAM and ROM after splitting, where check_circuit was confused by public inputs after circuit finalisation.
Also changed recursion to do the final check with check_circuit + an auxiliary function that check the recursive proof point pairing. 

# Checklist:

- [ ] I have reviewed my diff in github, line by line.
- [ ] Every change is related to the PR description.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this pull request to the issue(s) that it resolves.
- [ ] There are no unexpected formatting changes, superfluous debug logs, or commented-out code.
- [ ] There are no circuit changes, OR specifications in `/markdown/specs` have been updated.
- [ ] There are no circuit changes, OR a cryptographer has been assigned for review.
- [ ] I've updated any terraform that needs updating (e.g. environment variables) for deployment.
- [ ] The branch has been rebased against the head of its merge target.
- [ ] I'm happy for the PR to be merged at the reviewer's next convenience.
- [ ] New functions, classes, etc. have been documented according to the doxygen comment format. Classes and structs must have `@brief` describing the intended functionality.
- [ ] If existing code has been modified, such documentation has been added or updated.

### CODE REVIEW

File: cpp/src/barretenberg/proof_system/circuit_constructors/circuit_constructor_base.hpp [hunk 1]
```diff
@@ -255,7 +297,7 @@ template <typename Arithmetization> class CircuitConstructorBase {
         _failed = true;
         set_err(msg);
     }
-};
+}; // namespace proof_system
```
Comment (codygunton) [inline cpp/src/barretenberg/proof_system/circuit_constructors/circuit_constructor_base.hpp]: This is actually the end of the class definition, not the namespace.

File: cpp/src/barretenberg/honk/composer/composer_helper/ultra_honk_composer_helper.cpp [hunk 2]
```diff
@@ -291,6 +297,24 @@ std::shared_ptr<UltraHonkComposerHelper::Flavor::ProvingKey> UltraHonkComposerHe
     proving_key->table_3 = poly_q_table_column_3;
     proving_key->table_4 = poly_q_table_column_4;
 
+    // Copy memory read/write record data into proving key. Prover needs to know which gates contain a read/write
```
Comment (codygunton) [inline cpp/src/barretenberg/honk/composer/composer_helper/ultra_honk_composer_helper.cpp]: Since #520, this happens in `compute_witness`, right?

File: cpp/src/barretenberg/stdlib/recursion/verifier/verifier.test.cpp [hunk 3]
```diff
@@ -276,6 +276,63 @@ template <typename OuterComposer> class stdlib_verifier : public testing::Test {
...
     }
 
+    /**
+     * @brief Check the correctness of the recursive proof public inputs
+     *
+     * @details Circuit constructors have no notion of SRS and any proof-related stuff except for the existence of
+     * recursive proof-specific public inputs, so we can't check the recursive proof fully in check_circuit. So we use
+     * this additional function to check that the recursive proof points work.
+     *
+     * @return true
```
Comment (codygunton) [inline cpp/src/barretenberg/stdlib/recursion/verifier/verifier.test.cpp]: Return documentation is funny.

**Review by codygunton — APPROVED** [review]
Looks just a small amount of cleanup left.
