### PR TITLE
Unify pcs interfaces, fix IPA and make Honk commitment agnostic

### LINKED ISSUE #220: TODO: address several comments from Arijit in IPA commitment scheme

### PR DESCRIPTION
**Pull request by maramihali**
This PR closes #220, #236, #166 and:
* refactors the polynomial commitment schemes (pcs) interfaces in Honk to have unified interfaces and ensures usages of the pcs inside Honk are commitment agnostic
* improves documentations in the pcs folder
* resolves an issue in the IPA commentiment that was causing the proving system to fail when using IPA (in short: because the srs was being transform with the pippenger point table twice) and resolves some tech debt in the IPA component

Moreover, it advances work on issue #400 but, in order for this issue to be resolved, we further need to decide on structure and level of abstraction for Honk that enables us to run the same tests on IPA and KZG automatically (right now, to test IPA one would need to change the PCS-related parameters in the flavor manually). 

# Checklist:

- [ ] I have reviewed my diff in github, line by line.
- [ ] Every change is related to the PR description.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this pull request to the issue(s) that it resolves.
- [ ] There are no unexpected formatting changes, superfluous debug logs, or commented-out code.
- [ ] There are no circuit changes, OR specifications in `/markdown/specs` have been updated.
- [ ] There are no circuit changes, OR a cryptographer has been assigned for review.
- [ ] I've updated any terraform that needs updating (e.g. environment variables) for deployment.
- [ ] The branch has been rebased against the head of its merge target.
- [ ] I'm happy for the PR to be merged at the reviewer's next convenience.
- [ ] New functions, classes, etc. have been documented according to the doxygen comment format. Classes and structs must have `@brief` describing the intended functionality.
- [ ] If existing code has been modified, such documentation has been added or updated.

### CODE REVIEW

File: cpp/src/barretenberg/honk/pcs/kzg/kzg.hpp [hunk 1]
```diff
@@ -1,93 +1,65 @@
...
+                                      const Polynomial& polynomial,
+                                      ProverTranscript<Fr>& prover_trancript)
     {
         Polynomial quotient(polynomial);
         quotient[0] -= opening_pair.evaluation;
+        // Computes the coefficients for the quotient polynomial q(X) = (p(X) - v) / (X - r) through an FFT
         quotient.factor_roots(opening_pair.challenge);
-
-        return quotient;
+        auto quotient_commitment = ck->commit(quotient);
```
Comment (ledwards2225) [inline cpp/src/barretenberg/honk/pcs/kzg/kzg.hpp:39]: Just flagging this: Historically we have had to rely on the work_queue to compute commitments - we could not compute them directly inside of other functions. (This is due to the way we manually achieve parallelization in WASM). However with Charlie's recent "low memory prover" work, he's updated to WASI 20 (?) which has some native support for multithreading, eliminating the need for the work_queue. My understanding is that his work depends on some fairly experimental libraries so I think it's too early to say for sure whether we can say goodbye to the work_queue forever. All of this is to say that I think it's ok to compute this commitment directly for now but it's probably worth leaving a note just in case this has to be adjusted in the future.

Comment (maramihali) [reply cpp/src/barretenberg/honk/pcs/kzg/kzg.hpp:39]: That’s a very good point, thank you. Thought I left a comment

File: sol/lib/openzeppelin-contracts
Comment (Rumata888) [inline sol/lib/openzeppelin-contracts:1]: I'm not sure this is supposed to be here. Did you run git add * on the root?

Comment (maramihali) [reply sol/lib/openzeppelin-contracts:1]: It definitely doesn’t need to be there, sorry missed it. Thanks for spotting!

File: cpp/src/barretenberg/honk/flavor/ultra.hpp [hunk 2]
```diff
@@ -35,12 +36,15 @@ class Ultra {
...
+    // Note: UltraHonk will be run with KZG by default but temporarily we set the commitment to IPA to
+    // be able to do e2e tests with this pcs as well
+    using PCSParams = pcs::ipa::Params;
+    using PCS = pcs::ipa::IPA<PCSParams>;
 
     static constexpr size_t NUM_WIRES = CircuitConstructor::NUM_WIRES;
     // The number of multivariate polynomials on which a sumcheck prover sumcheck operates (including shifts). We often
     // need containers of this size to hold related data, so we choose a name more agnostic than `NUM_POLYNOMIALS`.
-    // Note: this number does not include the individual sorted list polynomials.
+    // Note: this number does not include the individual ultra list polynomials.
```
Comment (Rumata888) [inline cpp/src/barretenberg/honk/flavor/ultra.hpp]: What did you mean? We have sorted list polynomials as part of plookup argument

File: cpp/src/barretenberg/honk/proof_system/verifier.hpp [hunk 3]
```diff
@@ -20,9 +20,9 @@ template <typename Flavor> class StandardVerifier_ {
     bool verify_proof(const plonk::proof& proof);
 
     std::shared_ptr<VerificationKey> key;
-    std::map<std::string, Commitment> kate_g1_elements;
-    std::map<std::string, FF> kate_fr_elements;
-    std::shared_ptr<PCSVerificationKey> kate_verification_key;
+    std::map<std::string, Commitment> pcs_g1_elements;
```
Comment (Rumata888) [inline cpp/src/barretenberg/honk/proof_system/verifier.hpp]: If these are just commitments, maybe we should rename it to something like that? The g1_elements only has meaning in parining-based commitments

File: cpp/src/barretenberg/honk/proof_system/ultra_verifier.hpp [hunk 4]
```diff
@@ -21,9 +21,9 @@ template <typename Flavor> class UltraVerifier_ {
     bool verify_proof(const plonk::proof& proof);
 
     std::shared_ptr<VerificationKey> key;
-    std::map<std::string, Commitment> kate_g1_elements;
-    std::map<std::string, FF> kate_fr_elements;
-    std::shared_ptr<PCSVerificationKey> kate_verification_key;
+    std::map<std::string, Commitment> pcs_g1_elements;
```
Comment (Rumata888) [inline cpp/src/barretenberg/honk/proof_system/ultra_verifier.hpp]: I think the name is a bit misleading, since commitments don't have to be g1 elements for generic commitment schemes

File: cpp/src/barretenberg/honk/flavor/ultra.hpp (hunk 2 above)
Comment (maramihali) [reply cpp/src/barretenberg/honk/flavor/ultra.hpp]: Wups, accidental renaming, thanks for spotting!

File: cpp/src/barretenberg/honk/pcs/ipa/ipa.hpp [hunk 5]
```diff
@@ -2,81 +2,76 @@
...
-        std::vector<Commitment> R_elements(log_poly_degree);
-        size_t round_size = poly_degree;
+        // Iterate for log(poly_degree) rounds to compute the round commitments.
+        auto log_poly_degree = static_cast<size_t>(numeric::get_msb(poly_degree));
+        std::vector<GroupElement> L_elements(log_poly_degree);
+        std::vector<GroupElement> R_elements(log_poly_degree);
+        std::size_t round_size = poly_degree;
 
         for (size_t i = 0; i < log_poly_degree; i++) {
             round_size >>= 1;
```
Comment (Rumata888) [inline cpp/src/barretenberg/honk/pcs/ipa/ipa.hpp:78]: I'd add a todo to add one iteration of this cycle as a primitive to the work queue. Seems like the most  natural way to implement Work Queue for IPA

File: cpp/src/barretenberg/honk/pcs/ipa/ipa.hpp [hunk 6]
```diff
@@ -145,31 +131,30 @@ template <typename Params> class InnerProductArgument {
...
-                              const OpeningPair<Params>& opening_pair,
-                              size_t poly_degree,
-                              VerifierTranscript<Fr>& transcript)
+    static bool verify(std::shared_ptr<VK> vk,
+                       const OpeningClaim<Params>& opening_claim,
+                       VerifierTranscript<Fr>& transcript)
     {
-        auto commitment = transcript.template receive_from_prover<CommitmentAffine>("IPA:C");
-
+        // so we should get an OpeningClaim as parameter with
```
Comment (Rumata888) [inline cpp/src/barretenberg/honk/pcs/ipa/ipa.hpp]: Is this the full comment?

File: cpp/src/barretenberg/plonk/composer/composer_helper/composer_helper_lib.cpp [hunk 7]
```diff
@@ -49,7 +49,8 @@ std::shared_ptr<plonk::verification_key> compute_verification_key_common(
     auto circuit_verification_key = std::make_shared<plonk::verification_key>(
         proving_key->circuit_size, proving_key->num_public_inputs, vrs, proving_key->composer_type);
     // TODO(kesha): Dirty hack for now. Need to actually make commitment-agnositc
-    auto commitment_key = proof_system::honk::pcs::kzg::CommitmentKey(proving_key->circuit_size, "../srs_db/ignition");
+    auto commitment_key =
```
Comment (Rumata888) [inline cpp/src/barretenberg/plonk/composer/composer_helper/composer_helper_lib.cpp]: What changed here?

File: cpp/src/barretenberg/honk/proof_system/prover.cpp [hunk 8]
```diff
@@ -217,13 +217,14 @@ template <StandardFlavor Flavor> void StandardProver_<Flavor>::execute_shplonk_p
...
+ * - For KZG, this is the quotient commitment [W]_1
+ * - For IPA, the vectors L and R
  * */
-template <StandardFlavor Flavor> void StandardProver_<Flavor>::execute_kzg_round()
+template <StandardFlavor Flavor> void StandardProver_<Flavor>::execute_final_pcs_round()
 {
-    quotient_W = KZG::compute_opening_proof_polynomial(shplonk_output.opening_pair, shplonk_output.witness);
-    queue.add_commitment(quotient_W, "KZG:W");
+    PCS::compute_opening_proof(pcs_commitment_key, shplonk_output.opening_pair, shplonk_output.witness, transcript);
+    info("done");
```
Comment (Rumata888) [inline cpp/src/barretenberg/honk/proof_system/prover.cpp]: Do we need the info?

Comment (Rumata888) [reply cpp/src/barretenberg/honk/proof_system/prover.cpp]: Also, have you added the queue interaction into the KZG?

File: cpp/src/barretenberg/honk/flavor/ultra.hpp [hunk 9]
```diff
@@ -35,7 +36,10 @@ class Ultra {
     using GroupElement = G1::element;
     using Commitment = G1::affine_element;
     using CommitmentHandle = G1::affine_element;
-    using PCSParams = pcs::kzg::Params;
+    // Note: UltraHonk will be run with KZG by default but temporarily we set the commitment to IPA to
+    // be able to do e2e tests with this pcs as well
+    using PCSParams = pcs::ipa::Params;
```
Comment (Rumata888) [inline cpp/src/barretenberg/honk/flavor/ultra.hpp:42]: I think it would be better to create an ultra template and then instantiate it with IPA and KZG commitments separately since we'll need both. This way you are completely replacing it

**Review by Rumata888 — APPROVED** [review]

File: cpp/src/barretenberg/honk/flavor/ultra.hpp (hunk 9 above)
Comment (Rumata888) [reply cpp/src/barretenberg/honk/flavor/ultra.hpp:42]: Ah, we don't have that option since composer helper is not tempalted. I'd switch the Note to todo. Once we template it, we should immediately split

Comment (maramihali) [reply cpp/src/barretenberg/honk/flavor/ultra.hpp:42]: Yup, that's the task I'm workin on right now :)

File: cpp/src/barretenberg/honk/pcs/ipa/ipa.hpp (hunk 6 above)
Comment (maramihali) [reply cpp/src/barretenberg/honk/pcs/ipa/ipa.hpp]: leftover helper comment

File: cpp/src/barretenberg/honk/proof_system/prover.cpp (hunk 8 above)
Comment (maramihali) [reply cpp/src/barretenberg/honk/proof_system/prover.cpp]: No, I have temporarily taken out the work_queue from KZG to have the interfaces unifies and left a TODO in KZG to put it back when we integrate it in IPA as well. Adding a TODO here as well.

File: cpp/src/barretenberg/plonk/composer/composer_helper/composer_helper_lib.cpp (hunk 7 above)
Comment (maramihali) [reply cpp/src/barretenberg/plonk/composer/composer_helper/composer_helper_lib.cpp]: The `CommitmentKey` is inside Params now (see honk/pcs/commitment_key.hpp)
